### ISSUE TITLE
year as string

### ISSUE THREAD

**Issue by ErnstPfann** [sfakir/feiertagejs#17]
From the examples:
`var holidays2018 = feiertagejs.getHolidays('2018', 'BUND');`
try this for 2017:
`var holidays2017 = feiertagejs.getHolidays('2017', 'BUND');`
and get missing REFORMATIONSTAG.

Solution:
Write year as number:
`var holidays2017 = feiertagejs.getHolidays(2017, 'BUND');`
or **better** change code:
`if (year === 2017 || ...`
to:
`if (year == 2017 || ...`

**Comment by sfakir** [comment]
Dear ErnstPfann,
thank you for the request.
From what I got there are different outputs if you use integer or string as paramter. To ensure it is always and integer I will now internally convert it to Integer  -  no matter if you use string or not.

Please note: REFORMATIONSTAG is not availble in 'BUND', since it's limited to some states.

Update will be here tonight :)

Simon

**Comment by sfakir** [comment]
Solved in 1.2.2

**Comment by thetric** [comment]
@sfakir The Travis CI build is broken. Will you fix the issue or should I create a PR?
