### ISSUE TITLE
isSpecificHoliday

### ISSUE THREAD

**Issue by Tom-Neo** [sfakir/feiertagejs#46]
Works isSpecificHoliday with any date?
isSpecificHoliday(new Date('2021-12-25T09:30:00.000+01:00'), 'CHRISTIHIMMELFAHRT', 'ALL')

returns true. I was expecting it returns false.

**Comment by sfakir** [comment]
@Tom-Neo  Thank you for bringing up this topic and sorry for the late reply, I think I missed the notification.

You are right, the method had a bug, which allowed any holiday to be true, instead of the specific one. This was fixed in the latest version and also I added a unittest for this case.

Simon
